language: python

cache: pip

matrix:
    fast_finish: true
    include:
    - python: 3.6
    - python: 3.7
      sudo: required
      dist: xenial
    - python: 3.8-dev
      sudo: required
      dist: xenial
    allow_failures:
    - python: 3.8-dev

install:
    - pip install "setuptools>=40.1.0"
    - pip install -e .

before_script:
    - pip install -r requirements_dev.txt

script:
    - pytest -xvv tests
