language: python

cache: pip

python:
    - 3.5
    - 3.6

matrix:
    fast_finish: true
    include:
    - python: 3.7
      sudo: required
      dist: xenial
    - python: 3.8-dev
      sudo: required
      dist: xenial
    allow_failures:
    - python: 3.8-dev

install:
    - pip install -e .

script:
    - pytest -xvv tests
